
# tap repositories and their packages

## rcmdnk/file
tap rcmdnk/file
brew brew-file

tap 'homebrew/versions'

## caskroom/cask
tap caskroom/cask
brew brew-cask

# Other Homebrew packages
brew autoconf
brew lv
brew openssl
brew pkg-config
brew rbenv
brew ruby-build

# clone from Nakamura-san Brewfile
brew 'git'

brew 'direnv'

brew 'readline'
brew 'rbenv'
brew 'ruby-build'

brew 'mysql'
brew 'redis'

brew 'imagemagick'
brew 'ghostscript'
brew 'ffmpeg'
brew 'homebrew/versions/phantomjs198'


# Below applications were installed by Cask,
# but do not have corresponding casks.

#cask ==> We need to make Caskroom for the first time at /opt/homebrew-cask/Caskroom
#cask ==> We'll set permissions properly so we won't need sudo in the future
#cask Warning: nothing to list

# App Store applications
appstore Apple Configurator
appstore GarageBand
appstore iMovie
appstore iPhoto
appstore Keynote
appstore Numbers
appstore Pages
